apiVersion: v1
kind: Service
metadata:
  labels:
    app: factorio-server
  name: factorio-server
  namespace: default
spec:
  ports:
  - nodePort: 31407
    port: 34197
    protocol: UDP
    targetPort: 34197
  selector:
    app: factorio-server
  type: NodePort
